### ISSUE TITLE
GTK3: Only the first application icon is visible

### ISSUE THREAD

**Issue by City-busz** [mate-desktop/mate-netbook#26]
Steps to reproduce:
1. Add Window Picker applet to the panel.
2. Open multiple windows.
3. See that only the first application button has icon, other buttons are just empty space.

Package versions:
- mate-netbook (gtk3) 1.12.0
- mate-panel (gtk3) 1.12.0
- gtk3 3.18.5

**Comment by monsta** [comment]
Confirmed. The invisible icons are clickable though.
