### ISSUE TITLE
No underacorated Windows in Mate 1.12

### ISSUE THREAD

**Issue by RockOnHero** [mate-desktop/mate-netbook#27]
In Mate 1.12 the Applet does not undecorate the Windows anymore. On an maximized Window it provides a Close-Button. But without undecorating the Applet ist only a nice Window Picker. 
Feel free to delete this Issue, if there is any workaround etc.

Mate 1.12.0 on Linux Mint 17.2 via Romeo

**Comment by monsta** [comment]
Undecorating is done by ```mate-maximus```, not by Window Picker applet.

```
gsettings set org.mate.maximus undecorate true
```

**Comment by RockOnHero** [comment]
Thank you very much.
