### ISSUE TITLE
Applet doesn't work with additional themes

### ISSUE THREAD

**Issue by RockOnHero** [mate-desktop/mate-netbook#28]
When I use numix-gtk theme the applet turn grey instant of the numix color.

![vm](https://cloud.githubusercontent.com/assets/15233968/14746832/cc7236de-08b1-11e6-9f21-5a8004ca08ca.png)

**Comment by raveit65** [comment]
This means numix-gtk theme doesn't support mate-panel. I suggest to file out a report against numix theme.
Examples how to theme mate-panel can the developer find here.
https://github.com/mate-desktop/mate-themes

**Comment by RockOnHero** [comment]
My fault. Thank you for your advise.
