### ISSUE TITLE
Migrate mate-netbook to GtkApplication

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop/mate-netbook#29]
Debian has raised the following bug:

  * **mate-netbook** - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827231

This MATE component needs migrating to GtkApplication:

  * https://developer.gnome.org/gtk3/3.20/gtk-migrating-unique-GtkApplication.html

**Comment by sc0w** [comment]
@flexiondotorg 

> Debian has raised the following bug:
> 
>     mate-netbook - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827231

The link of debian bug is wrong

The link is:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827229

@monsta @raveit65 

by the way, I solved this bug with **Gapplication**, will it work in gtk2 ?
