### ISSUE TITLE
Add an unmaximize button next to the close button

### ISSUE THREAD

**Issue by Gnalldo** [mate-desktop/mate-netbook#30]
The is a repetitive task of right clicking the icon and going to unmaximize would be much more intuitive with a button next to the title where the close button is.

**Comment by cyber-doug** [comment]
Sorry, did you know you could double-click the title area of the applet to unmaximize, just like we do in Unity? It may not be good for everyone, but it works better than right clicking. Good luck.

**Comment by Gnalldo** [comment]
I'm aware of that, but my issue is, I want to eliminate the title bar to save that extra screen space. I prefer to hide the window decoration when maximized, but that leaves me with no other way to unmazimize my window. What I really need I just a min/max/close applet. Thanks anyway.

**Comment by vendelin8** [comment]
For a quick fix, you could use keyboard shortcuts:
Alt+F5 unmaximizes the window
Alt+F10 toggles between maximized and unmaximized
