### ISSUE TITLE
[Feature Request]: mate-window-picker-applet - Show windows only for current workspace

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/mate-netbook#41]
Currently icons for every window regardless of current workspace are displayed in the applet.
This does not match the workflow people are used to when using the Window List applet.

**Comment by milouse** [comment]
There is a preference for that. Thus I think this issue should be closed now. (poke @raveit65 or @flexiondotorg ?)

**Comment by vkareh** [comment]
Correct, right-click on the applet handle (the three dots on the left side of it) and select Preferences. In there, "Show all windows" toggles between current and all workspaces
