### ISSUE TITLE
CSD applications gain second decoration if started maximized, then unmaximized.

### ISSUE THREAD

**Issue by Cpt-Derp** [mate-desktop/mate-netbook#44]
[First reported here, found out to be a bug with mate-netbook rather than Marco](https://github.com/mate-desktop/marco/issues/428)

#### Expected behaviour
CSD apps stay with their own decoration upon unmaximizing.

#### Actual behaviour
mate-netbook decorates them twice upon unmaximizing.

#### Steps to reproduce the behaviour
Start any CSD application maximized, then unmaximize it.

#### MATE general version
1.20.1

#### Package version
1.20.1-2ubuntu1

#### Linux Distribution
Ubuntu MATE 18.04.1 amd64
Also confirmed on LiveCD of the same distro, ruling out a configuration issue

#### Link to downstream report of your Distribution
None

The decoration also seems to come with a new border that is wide and transparent. The app in the background for instance is Discord and not anything Firefox.

![image](https://user-images.githubusercontent.com/3199836/45923034-a3ff4980-bea8-11e8-9d47-b487e5bbc729.png)

**Comment by monsta** [comment]
Yes, known issue with mate-maximus: https://github.com/mate-desktop/mate-netbook/issues/14
