### ISSUE TITLE
Segfault for mate-netbook 1.21.0 when running "bin/mate-maximus" and strange behaviour difference between mate-maximus --help and mate-maximus --version

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop/mate-netbook#46]
Hello there. I am getting a bit slightly confusing results, so let me start with
what seems to work properly first:

- When I issue:

    mate-maximus --help

I almost instantly get this text result on the commandline:

Usage:
  mate-maximus [OPTION?] - Maximus

Help Options:
  -h, --help               Show help options
  --help-all               Show all help options
  --help-gtk               Show GTK+ Options

Application Options:
  -v, --version            Prints the version number
  -m, --no-maximize        Do not automatically maximize every window
  --display=DISPLAY        X display to use

So far so fine. That seems to work as intended.

So now to things that don't quite seem to work as well.

Then I try to get the version, and when I do so, I get:

    mate-maximus --version

libmozjs185.so.1.0: cannot open shared object file: No such file or directory
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
no maximize: true

I think the first two lines can be ignored, but I kept it anyway (I think this is
unrelated, just glib/gio and libmozjs being confused about one another).

What I get from the above --version flag is this strange line called
"no maximize: true"

I am not sure if this should occur? But anyway, the window stays
where it is and nothing else is printed. I don't get the version 
information from the commandline.

I am not currently running mate-desktop as I write this, I run fluxbox,
but in my opinion, the behaviour is quite straneg; this "no maximize: true"
part should never appear, I think. I only asked to query the --version,
so I would expect a version string such as 1.20.1 or something like
that. Note that other mate-desktop components behave like this,
so without knowing the code of mate-netbook, I believe it behaves
slightly differently.

I am not sure why nothing shows afterwards but I think some kind of
invisible widget may be started or something, since I also don't see
the cursor or anything after doing "mate-maximus --version". Very
strange.

I also tried mate-netbook 1.21.0 but when I try to run mate-maximus 
with any option I only get a segfault.

I compile everything from source so I expect problems to happen,
but the behaviour is pretty awkward to me, and the other mate-desktop
components behave more or less correct (at the least from what I
can see). I may have some version mish-mash due to having both
components from 1.21.0 and 1.20.0 available here, but I am not
sure this could explain why mate-maximus would behave so strangely.

I would suggest that the code leading up to --version may be investigated
when someone may have a bit of time - I assume that it may be branching
off somewhere into that strange "no maximize: true" which I don't think
should possibly be shown ever.

GCC is version 8.1.0, binutils is latest git checkout etc... most is quite recent here,
except for glibc which is 2.23 from the latest slackware release.

**Comment by bunder2015** [comment]
I get segfaults from mate-maximus as well, but I believe it might come from 92910b6.

```
Thread 1 "mate-maximus" received signal SIGSEGV, Segmentation fault.
0x00007ffff700556d in ?? () from /usr/lib64/libgdk-3.so.0
(gdb) bt
#0  0x00007ffff700556d in ?? () from /usr/lib64/libgdk-3.so.0
#1  0x00007ffff70055fe in gdk_x11_display_error_trap_push () from /usr/lib64/libgdk-3.so.0
#2  0x00005555555571f2 in ?? ()
#3  0x00007ffff5ba0ae7 in __libc_start_main () from /lib64/libc.so.6
#4  0x000055555555723a in ?? ()
```

**Comment by bunder2015** [comment]
thanks!
