### ISSUE TITLE
mate-netbook missing from mate-desktop 1.28.x release tarballs

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-netbook#69]
Arch has updated MATE from 1.26.x to 1.28.x ; performing a post-upgrade QC of my system packages I find this sub-project is missing from the master deployment folder at https://pub.mate-desktop.org/releases/1.28/  hence Arch has no upgrade for it available.

In Arch, `mate-netbook` is a member of a meta-group `mate-extra` so this package gets installed as a dep; as a disclaimer I don't much know what this is used for and I don't think I use it on my system, however after noticing that this project was built for the 1.27.x dev branch/releases it's probably expected this should have been upgraded/included in 1.28.x?  (meaning it's not deprecated, still active / useful for users?)

If this sub-project is considered deprecated with 1.28.x I'll file an issue upstream in Arch for it's removal, just looking for the correct next steps. Thanks!

**Comment by lukefromdc** [comment]
Anyone else on the team following this? This is not a package I use or have worked on, it was designed to help make things fit on machines that commonly had a 600x1280 screen.

Leaving it to the others to decide what we want to do with this.

**Comment by immolo** [comment]
My eeepc 901 at 1024x600 works fine without is the best I can offer however I am following this to see if I can drop it from Gentoo as well.

Currently all 1.28 releases don't include it so hopefully we will get some user feedback soon to see if anyone does have a need for it.
